title: "AdventureWorks on Fabric & Power BU"
description: "Interactive Power BI reports built on the AdventureWorks 2016 Extended dataset."
theme: jekyll-theme-merlot
markdown: kramdown
show_downloads: false

# Optional metadata
author: "Anil Jacob"
github:
  is_project_page: true
  owner_url: "https://github.com/AwesomeAnil"
  repository_url: "https://github.com/AwesomeAnil/adventureworks-2016-extended"

# Exclude unnecessary files from site build
exclude:
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock

