title: "Adventure Works on Fabric & Power BI"
description: "Customer Portfolio management with AdventureWorks 2016 Extended dataset on Fabric."
theme: jekyll-theme-leap-day@v0.2.0
show_downloads: false

# Optional metadata
author: "Anil Jacob"
github:
  is_project_page: true
  owner_url: "https://github.com/AwesomeAnil"
  repository_url: "https://github.com/AwesomeAnil/adventureworks-2016-extended"

# Exclude unnecessary files from site build
exclude:
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
